
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SWP391Hommate
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: none
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8090