
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SWP391Hommate
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: none
        format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  servlet:
        multipart:
          max-file-size: 5MB
          max-request-size: 5MB

  http:
        multipart:
          enabled: false
server:
  port: 8090

