server:
  port: ${SERVER_PORT:8080}
  url: ${SERVER_URL:http://localhost:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    -url: jdbc:mysql://${DATASOURCE_HOST:localhost:3306}/${DATASOURCE_DATABASE:task_service}
    -username: ${DATASOURCE_USERNAME:root}
    -password: ${DATASOURCE_PASSWORD:1234}

  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

aws:
  bucket: ${AWS_BUCKET_NAME:}
  region: ${AWS_BUCKET_REGION:}
  access-key: ${AWS_ACCESS_KEY:}
  secret-key: ${AWS_SECRET_KEY:}

google:
  client-id: ${GOOGLE_CLIENT_ID:}
  client-secret: ${GOOGLE_CLIENT_SECRET:}
  auth-server-url: ${GOOGLE_AUTH_URL:}
